CC = gcc

ejecutars: server
	gnome-terminal
	gnome-terminal
	gnome-terminal
	gnome-terminal
	reset
	./server

ejecutable_serv: p1-dogProgram_server.c
	$(CC) p1-dogProgram_server.c -o server

ejecutarc: client
	./client

ejecutable_serv: p1-dogProgram_client.c
	$(CC) p1-dogProgram_client.c -o client

